/**
 * TypeScript Client Generator
 * 
 * Generates fully functional TypeScript client code from parsed contract ABIs.
 */

import { ParsedContract, ParsedFunction, ParsedArg } from './abi-parser';
import dedent from 'dedent';

export class ClientGenerator {
  generate(contract: ParsedContract, contractAddress: string): string {
    const parts: string[] = [];

    // Header
    parts.push(this.generateHeader(contract.name));

    // Imports
    parts.push(this.generateImports());

    // Type imports
    parts.push(this.generateTypeImports(contract));

    // Client class
    parts.push(this.generateClientClass(contract, contractAddress));

    // Factory function
    parts.push(this.generateFactory(contract));

    return parts.filter(p => p.length > 0).join('\n\n');
  }

  private generateHeader(contractName: string): string {
    return dedent`
      /**
       * Auto-generated client for ${contractName} contract
       * 
       * Generated by @sf-protocol/cli codegen
       * Do not edit manually - regenerate using: sf-protocol codegen
       */
    `;
  }

  private generateImports(): string {
    return dedent`
      import { BaseClient } from '@sf-protocol/core';
      import { NetworkConfig } from '@sf-protocol/core';
      import { ClarityValue, cvToValue, serializeCV } from '@stacks/transactions';
      import { callReadOnlyFunction, broadcastTransaction } from '@stacks/transactions';
    `;
  }

  private generateTypeImports(contract: ParsedContract): string {
    const types: string[] = [];

    // Add arg types
    contract.readOnlyFunctions
      .concat(contract.publicFunctions)
      .filter(f => f.args.length > 0)
      .forEach(f => {
        const typeName = this.toPascalCase(f.name) + 'Args';
        types.push(typeName);
      });

    // Add result types
    contract.readOnlyFunctions
      .concat(contract.publicFunctions)
      .forEach(f => {
        const typeName = this.toPascalCase(f.name) + 'Result';
        types.push(typeName);
      });

    // Add contract interface
    types.push(contract.name + 'Contract');

    return `import { ${types.join(', ')} } from './${this.toKebabCase(contract.name)}.types';`;
  }

  private generateClientClass(contract: ParsedContract, contractAddress: string): string {
    const readOnlyMethods = contract.readOnlyFunctions
      .map(f => this.generateReadOnlyMethod(f, contract.name))
      .join('\n\n  ');

    const publicMethods = contract.publicFunctions
      .map(f => this.generatePublicMethod(f, contract.name))
      .join('\n\n  ');

    return dedent`
      export class ${contract.name}Client extends BaseClient implements ${contract.name}Contract {
        private contractAddress = '${contractAddress}';

        constructor(config: NetworkConfig) {
          super(config);
        }

        // Read-only functions
        ${readOnlyMethods}

        // Public functions
        ${publicMethods}
      }
    `;
  }

  private generateReadOnlyMethod(func: ParsedFunction, contractName: string): string {
    const resultType = this.toPascalCase(func.name) + 'Result';
    const clarityName = func.clarityName;

    if (func.args.length === 0) {
      return dedent`
        async ${func.name}(): Promise<${resultType}> {
          const result = await callReadOnlyFunction({
            network: this.network,
            contractAddress: this.contractAddress.split('.')[0],
            contractName: this.contractAddress.split('.')[1],
            functionName: '${clarityName}',
            functionArgs: [],
            senderAddress: this.contractAddress.split('.')[0]
          });

          return this.parseResult(result) as ${resultType};
        }
      `;
    }

    const argsType = this.toPascalCase(func.name) + 'Args';
    const argConversions = func.args
      .map(arg => this.generateArgConversion(arg))
      .join('\n    ');

    return dedent`
      async ${func.name}(args: ${argsType}): Promise<${resultType}> {
        const functionArgs = [
      ${argConversions}
        ];

        const result = await callReadOnlyFunction({
          network: this.network,
          contractAddress: this.contractAddress.split('.')[0],
          contractName: this.contractAddress.split('.')[1],
          functionName: '${clarityName}',
          functionArgs,
          senderAddress: this.contractAddress.split('.')[0]
        });

        return this.parseResult(result) as ${resultType};
      }
    `;
  }

  private generatePublicMethod(func: ParsedFunction, contractName: string): string {
    const resultType = this.toPascalCase(func.name) + 'Result';
    const clarityName = func.clarityName;

    if (func.args.length === 0) {
      return dedent`
        async ${func.name}(): Promise<string> {
          // Returns transaction ID - use waitForTransaction to get result
          const txOptions = {
            contractAddress: this.contractAddress.split('.')[0],
            contractName: this.contractAddress.split('.')[1],
            functionName: '${clarityName}',
            functionArgs: [],
            network: this.network,
            // Additional transaction options should be provided by caller
          };

          // Transaction building logic here
          throw new Error('Public function calls require wallet integration');
        }
      `;
    }

    const argsType = this.toPascalCase(func.name) + 'Args';
    const argConversions = func.args
      .map(arg => this.generateArgConversion(arg))
      .join('\n    ');

    return dedent`
      async ${func.name}(args: ${argsType}): Promise<string> {
        // Returns transaction ID - use waitForTransaction to get result
        const functionArgs = [
      ${argConversions}
        ];

        const txOptions = {
          contractAddress: this.contractAddress.split('.')[0],
          contractName: this.contractAddress.split('.')[1],
          functionName: '${clarityName}',
          functionArgs,
          network: this.network,
          // Additional transaction options should be provided by caller
        };

        // Transaction building logic here
        throw new Error('Public function calls require wallet integration');
      }
    `;
  }

  private generateArgConversion(arg: ParsedArg): string {
    const clarityType = arg.type.clarityType;

    switch (clarityType) {
      case 'uint128':
        return `      uintCV(args.${arg.name}), // ${arg.name}`;
      case 'int128':
        return `      intCV(args.${arg.name}), // ${arg.name}`;
      case 'bool':
        return `      boolCV(args.${arg.name}), // ${arg.name}`;
      case 'principal':
        return `      principalCV(args.${arg.name}), // ${arg.name}`;
      case 'string-ascii':
      case 'string-utf8':
        return `      stringCV(args.${arg.name}), // ${arg.name}`;
      default:
        return `      args.${arg.name}, // TODO: Convert ${clarityType} to ClarityValue`;
    }
  }

  private generateFactory(contract: ParsedContract): string {
    return dedent`
      /**
       * Create a new ${contract.name} client instance
       */
      export function create${contract.name}Client(config: NetworkConfig): ${contract.name}Client {
        return new ${contract.name}Client(config);
      }
    `;
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private toKebabCase(str: string): string {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  }
}

export function generateClient(
  contract: ParsedContract,
  contractAddress: string
): string {
  const generator = new ClientGenerator();
  return generator.generate(contract, contractAddress);
}
