/**
 * TypeScript Type Definition Generator
 * 
 * Generates TypeScript type definitions from parsed contract ABIs.
 */

import { ParsedContract, ParsedFunction, ParsedArg, ParsedMap } from './abi-parser';
import dedent from 'dedent';

export class TypeGenerator {
  generate(contract: ParsedContract): string {
    const parts: string[] = [];

    // Header
    parts.push(this.generateHeader(contract.name));

    // Imports
    parts.push(this.generateImports());

    // Function argument types
    parts.push(this.generateFunctionArgTypes(contract));

    // Function return types
    parts.push(this.generateFunctionReturnTypes(contract));

    // Contract interface
    parts.push(this.generateContractInterface(contract));

    return parts.filter(p => p.length > 0).join('\n\n');
  }

  private generateHeader(contractName: string): string {
    return dedent`
      /**
       * Auto-generated TypeScript definitions for ${contractName} contract
       * 
       * Generated by @sf-protocol/cli codegen
       * Do not edit manually - regenerate using: sf-protocol codegen
       */
    `;
  }

  private generateImports(): string {
    return dedent`
      import { BigIntString, Principal } from '@sf-protocol/core';
      import { ClarityValue } from '@stacks/transactions';
    `;
  }

  private generateFunctionArgTypes(contract: ParsedContract): string {
    const allFunctions = [
      ...contract.readOnlyFunctions,
      ...contract.publicFunctions
    ];

    const types = allFunctions
      .filter(f => f.args.length > 0)
      .map(f => this.generateFunctionArgType(f))
      .join('\n\n');

    return types;
  }

  private generateFunctionArgType(func: ParsedFunction): string {
    const typeName = this.toPascalCase(func.name) + 'Args';
    const fields = func.args
      .map(arg => `  ${arg.name}: ${arg.type.tsType};`)
      .join('\n');

    return dedent`
      export interface ${typeName} {
      ${fields}
      }
    `;
  }

  private generateFunctionReturnTypes(contract: ParsedContract): string {
    const allFunctions = [
      ...contract.readOnlyFunctions,
      ...contract.publicFunctions
    ];

    const types = allFunctions
      .map(f => this.generateFunctionReturnType(f))
      .join('\n\n');

    return types;
  }

  private generateFunctionReturnType(func: ParsedFunction): string {
    const typeName = this.toPascalCase(func.name) + 'Result';
    
    if (func.returnType.isResponse) {
      return dedent`
        export type ${typeName} = ${func.returnType.tsType};
      `;
    }

    return dedent`
      export type ${typeName} = ${func.returnType.tsType};
    `;
  }

  private generateContractInterface(contract: ParsedContract): string {
    const readOnlyMethods = contract.readOnlyFunctions
      .map(f => this.generateMethodSignature(f))
      .join('\n  ');

    const publicMethods = contract.publicFunctions
      .map(f => this.generateMethodSignature(f))
      .join('\n  ');

    return dedent`
      export interface ${contract.name}Contract {
        // Read-only functions
      ${readOnlyMethods}

        // Public functions
      ${publicMethods}
      }
    `;
  }

  private generateMethodSignature(func: ParsedFunction): string {
    const resultType = this.toPascalCase(func.name) + 'Result';
    
    if (func.args.length === 0) {
      return `  ${func.name}(): Promise<${resultType}>;`;
    }

    const argsType = this.toPascalCase(func.name) + 'Args';
    return `  ${func.name}(args: ${argsType}): Promise<${resultType}>;`;
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

export function generateTypes(contract: ParsedContract): string {
  const generator = new TypeGenerator();
  return generator.generate(contract);
}
